### ISSUE TITLE
Delete/Close all old issues/PRs/branches

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/shield-studies-addon-utils#117] opened 2018-03-09 22:14 UTC
If there's anything valuable in these old artifacts, let's create a new issue that distills all of that in one place. Ideally we have only recently made PRs/issues that are still relevant and clearly defined at the end.

**Comment by motin** [comment] 2018-03-14 14:42
Good idea. This issue is fine for that purpose. Suggested rename: **Review and distill anything valuable in older issues/PRs/branches before closing them**

**Comment by gregglind** [comment] 2018-04-02 19:44
closing as duplicate of #112

**Closed by gregglind** 2018-04-02 19:44 UTC
